---
server:
  port: 9001
keycloak:
  realm: alunwcom
  auth-server-url: https://auth.alunw.com/auth/
  ssl-required: external
  resource: moany-api
  use-resource-role-mappings: true
  bearer-only: true
