---
server:
  port: 9001
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.alunw.com/auth/realms/alunwcom
          jwk-set-uri: https://auth.alunw.com/auth/realms/alunwcom/protocol/openid-connect/certs

