---
server:
  port: 9001
keycloak:
  realm: alunwcom
  auth-server-url: https://auth.alunw.com/auth/
  ssl-required: external
  resource: moany-api
  use-resource-role-mappings: true
  bearer-only: true

# TODO Added to resolve circular reference issue when upgrading from Spring Boot 2.5 to 2.6 - need to analyse actual issue
spring:
  main:
    allow-circular-references: true
